// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoJQbbwVXmT1pkin-UXE9KtkR-BM9c3ME',
    appId: '1:282537712616:android:6a71e7fef5032cd996625d',
    messagingSenderId: '282537712616',
    projectId: 'likealocal-final-8b198',
    storageBucket: 'likealocal-final-8b198.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBheaMdydQR5nyXVHXPK8Tl6TE5fHMOq40',
    appId: '1:282537712616:web:99a546cdbd2b882296625d',
    messagingSenderId: '282537712616',
    projectId: 'likealocal-final-8b198',
    authDomain: 'likealocal-final-8b198.firebaseapp.com',
    storageBucket: 'likealocal-final-8b198.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBheaMdydQR5nyXVHXPK8Tl6TE5fHMOq40',
    appId: '1:282537712616:web:c7276d4aa972ac4796625d',
    messagingSenderId: '282537712616',
    projectId: 'likealocal-final-8b198',
    authDomain: 'likealocal-final-8b198.firebaseapp.com',
    storageBucket: 'likealocal-final-8b198.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYLUsyJyUPZZq3zBtZc3t9MLrJAF0B20w',
    appId: '1:282537712616:ios:d1f4e0cd94ee9b1996625d',
    messagingSenderId: '282537712616',
    projectId: 'likealocal-final-8b198',
    storageBucket: 'likealocal-final-8b198.firebasestorage.app',
    iosBundleId: 'com.example.likealocalMobile',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYLUsyJyUPZZq3zBtZc3t9MLrJAF0B20w',
    appId: '1:282537712616:ios:d1f4e0cd94ee9b1996625d',
    messagingSenderId: '282537712616',
    projectId: 'likealocal-final-8b198',
    storageBucket: 'likealocal-final-8b198.firebasestorage.app',
    iosBundleId: 'com.example.likealocalMobile',
  );

}