// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACaz64-DqhrDHUTVF6nKJxq5zM8An2-AQ',
    appId: '1:667443185710:android:42ae6c570adbd1e08877bf',
    messagingSenderId: '667443185710',
    projectId: 'likealocal-new-bb959',
    storageBucket: 'likealocal-new-bb959.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYG5to9H8hPoPqN0DiGP8Ep6wAWdQGpnE',
    appId: '1:667443185710:web:db383460edac256c8877bf',
    messagingSenderId: '667443185710',
    projectId: 'likealocal-new-bb959',
    authDomain: 'likealocal-new-bb959.firebaseapp.com',
    storageBucket: 'likealocal-new-bb959.firebasestorage.app',
    measurementId: 'G-Q29EYE496C',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYG5to9H8hPoPqN0DiGP8Ep6wAWdQGpnE',
    appId: '1:667443185710:web:3128ec6ab0b246328877bf',
    messagingSenderId: '667443185710',
    projectId: 'likealocal-new-bb959',
    authDomain: 'likealocal-new-bb959.firebaseapp.com',
    storageBucket: 'likealocal-new-bb959.firebasestorage.app',
    measurementId: 'G-60EHLLHXT5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWRzmfmrC7SL0uis2RymAoVpzrfckNd_Q',
    appId: '1:667443185710:ios:6a80fb589360e8348877bf',
    messagingSenderId: '667443185710',
    projectId: 'likealocal-new-bb959',
    storageBucket: 'likealocal-new-bb959.firebasestorage.app',
    iosBundleId: 'com.example.likealocalMobile',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWRzmfmrC7SL0uis2RymAoVpzrfckNd_Q',
    appId: '1:667443185710:ios:6a80fb589360e8348877bf',
    messagingSenderId: '667443185710',
    projectId: 'likealocal-new-bb959',
    storageBucket: 'likealocal-new-bb959.firebasestorage.app',
    iosBundleId: 'com.example.likealocalMobile',
  );

}